apiVersion: v1
kind: Pod
metadata:
  name: data
spec:
   containers
   - name: data
     image: nginx
     volumeMounts: 
      - name: data
        mountPath: /etc/cert-data
   volumes:
   - name: data
     secret:
         secretName: my-tls-secret    
   imagePullSecrets
   - name: emigrate
