apiVersion: v1
kind: Service
metadata:
  name: gatewayservice-service
spec:
  selector:
      app: gateway
  type: LoadBalancer
  externalIPs:
  - 192.168.150.16
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
   
