apiVersion: v1
kind: Service
metadata:
  name: emigrate-gateway
spec:
  type: LoadBalancer
  externalIPs:
  - 192.168.150.16 
  selector:
    app: gateway  # Selects pods from app-deployment-1
  ports:
    - name: port1
      protocol: TCP
      port: 8081
      targetPort: 8081

  ports:
    - name: port2
      protocol: TCP
      port: 8181
      targetPort: 8181	  

  ports:
    - name: port3
      protocol: TCP
      port: 8084
      targetPort: 8084

  ports:
    - name: port4
      protocol: TCP
      port: 8083
      targetPort: 8083

  ports:
    - name: port5
      protocol: TCP
      port: 8080
      targetPort: 8080

  ports:
    - name: port6
      protocol: TCP
      port: 8092
      targetPort: 8092

  ports:
    - name: port7
      protocol: TCP
      port: 8086
      targetPort: 8086

  ports:
    - name: port8
      protocol: TCP
      port: 8094
      targetPort: 8094

  ports:
    - name: port9
      protocol: TCP
      port: 8082
      targetPort: 8082

  ports:
    - name: port10
      protocol: TCP
      port: 8085
      targetPort: 8085

  ports:
    - name: port11
      protocol: TCP
      port: 8087
      targetPort: 8087	 

  ports:
    - name: port12
      protocol: TCP
      port: 8088
      targetPort: 8088
