---
- name: Create Calico Config
  become: true
  template:
    src: "calico.j2"
    dest: "{{ calico_config_path }}"
  delegate_to: "{{groups['k8s-master'][0]}}"  

- name: Configure Calico networking.
  command: "kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.27.0/manifests/tigera-operator.yaml"
  register: calico_result
  changed_when: "'created' in calico_result.stdout"
  delegate_to: "{{groups['k8s-master'][0]}}"  

- name: Configure CIDR Range
  command: "kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f {{ calico_config_path }}"
  delegate_to: "{{groups['k8s-master'][0]}}"  
   
  