apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana
  namespace: grafana
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  nfs:
    path: /workspace/shared/promgrafana
    server: 192.168.150.16   # NFS server IP address
  storageClassName: promgraf
  mountOptions:
    - hard
    - nfsvers=4.1
