---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: grafana
  name: grafana
spec:
  storageClassName: promgraf
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
