---
- name: Ensure dependencies are installed.
  become: true
  package: name=curl state=present

- name: Adding yum kubernetes repository
  become: true
  yum_repository:
    name: Kubernetes
    baseurl: "https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version }}/rpm/"
    enabled: yes
    gpgcheck: yes
    description: Kubernetes yum repo
    gpgkey: "https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version }}/rpm/repodata/repomd.xml.key"
   # exclude: kubelet kubeadm kubectl cri-tools kubernetes-cni

- name: Install Kubernetes packages.
  become: true
  package:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
  notify: restart kubelet
  with_items: "{{ kubernetes_packages }}"

- name: Adding Docker GPG
  become: true
  rpm_key:
    key: "{{ docker_yum_gpg_key }}" 
    state: present

- name: Add Docker repository.
  become: true
  get_url:
    url: "https://download.docker.com/linux/centos/docker-ce.repo"
    dest: '/etc/yum.repos.d/docker-ce.repo'
    owner: root
    group: root
    mode: 0644

  
- name: Ensure container-selinux is installed.
  become: true
  package:
    name: container-selinux
    state: present   

- name: Ensure containerd is installed.
  become: true
  package:
    name: "{{ containerd_package }}"
    state: present
  register: ctdInst
- name: containerd enabled
  become: true
  service:
    name: containerd
    state: "{{ containerd_service_state }}"
    enabled: "{{ containerd_service_enabled }}"     
  when: ctdInst is succeeded

- name: Setup containerd
  become: true
  shell: |
    pause_image=kubeadm config images list | grep pause:

    containerd config default | sudo tee /etc/containerd/config.toml >/dev/null 2>&1
    sed -i 's/SystemdCgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml
    sed -i "s/pause:3.6/pause:3.9/g" /etc/containerd/config.toml
    systemctl restart containerd
    systemctl enable containerd
    systemctl status containerd

- name: Swapoff and Selinux off
  become: true
  shell: |
    swapoff -a
    sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
    setenforce 0
    sed -i --follow-symlinks 's/SELINUX=enforcing/SELINUX=permissive/g' /etc/sysconfig/selinux

- name: kubeadm images pull
  become: true
  command: >
    kubeadm config images pull

- name: Enable kubelet
  become: true
  shell: |
     systemctl enable --now kubelet