apiVersion: v1
kind: Service
metadata:
  name: emigrate-ui-service
spec:
  selector:
      app: emigrate-ui
  type: LoadBalancer
  externalIPs:
  - 192.168.150.16
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30029 
   
