---
- stat: path=/etc/kubernetes/admin.conf
  become: true
  register: st

- name: Make config directory
  become: true
  file:
    path: "{{ kubernetes_kubeadm_kubelet_config_file_path | dirname }}"
    state: directory
  when: not st.stat.exists

- name: Merge Kubeadm template
  become: true
  template:
    src: "kubeadm-cluster-config.j2"
    dest: "{{ kubernetes_kubeadm_kubelet_config_file_path }}"
  when: not st.stat.exists

- name: Initialize Kubernetes control plane with kubeadm init
  become: true
  command: >
    kubeadm init 
    --config {{ kubernetes_kubeadm_kubelet_config_file_path }}
    --ignore-preflight-errors=all
  register: kubeadmin_init
  when: not st.stat.exists

- name: Ensure .kube directory exists.
  file:
    path: ~/.kube
    state: directory
    mode: 0755

- name: Symlink the kubectl admin.conf to ~/.kube/conf.
  become: true
  file:
    src: /etc/kubernetes/admin.conf
    dest: /home/vagrant/.kube/config
    state: link
    mode: 0644
    owner: vagrant
    group: vagrant

- name: "fetch k8s certificates"
  become: true
  fetch:
    src: /etc/kubernetes/pki/{{item}}
    dest: /tmp/kubeadm-ha/pki/{{item}}
    flat: yes
  with_items:
    - ca.crt
    - ca.key
    - sa.key
    - sa.pub
    - front-proxy-ca.crt 
    - front-proxy-ca.key

- name: "get etcd certs from master1"
  become: true
  fetch:
    src: /etc/kubernetes/pki/etcd/{{item}}
    dest: /tmp/kubeadm-ha/pki/etcd/{{item}}
    flat: yes
  with_items:
    - ca.crt
    - ca.key

- name: "get admin conf from master 1"
  become: true
  fetch:
    src: /etc/kubernetes/{{item}}
    dest: /tmp/kubeadm-ha/{{item}}
    flat: yes
  with_items:
    - admin.conf